### ISSUE TITLE
refactor: remove y_hat_int from eval_dataset

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-model-training#447]
Adds confusion, and seems to not add any value?

AFAIK, it's the predicted classes when the model chooses its own threshold. I'm not sure we'd ever want to use that? :-)

@bokajgd, @KennethEnevoldsen, @HLasse, This is potentially a very large change. any thoughts before I go ahead and make it happen?

**Comment by KennethEnevoldsen** [comment]
I agree with Lasse. I don't have the time to do this refactorization before going to the US. I however think that there is no reason to fix it unless you are already working with the code.

**Comment by MartinBernstorff** [comment]
Oh, totally - this occurred to me because it had caused confusion with Signe and Sara. I'll remove it.

**Comment by bokajgd** [comment]
It doesn't seem to be a major change at all. It is only used in one function `create_performance_by_timedelta()` where it can easily be replaced by `y_hat_probs.round()`. All other mentions should be fine to just remove. :)

**Comment by MartinBernstorff** [comment]
Excellent, I'll get right on this.
